# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/marise',
                'doc_host': 'https://franckalbinet.github.io',
                'git_url': 'https://github.com/franckalbinet/marise',
                'lib_path': 'marise'},
  'syms': { 'marise.metadata': { 'marise.metadata.dict_to_string': ('metadata.html#dict_to_string', 'marise/metadata.py'),
                                 'marise.metadata.read_metadata': ('metadata.html#read_metadata', 'marise/metadata.py'),
                                 'marise.metadata.read_metadata_from_directory': ( 'metadata.html#read_metadata_from_directory',
                                                                                   'marise/metadata.py')}}}
